<?php

$material_icons = [
	['family' => 'material', 'style' => 'solid', 'name' => '3d rotation', 'unicode' => '&#xe84d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'ac unit', 'unicode' => '&#xeb3b;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'access alarm', 'unicode' => '&#xe190;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'access alarms', 'unicode' => '&#xe191;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'access time', 'unicode' => '&#xe192;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'accessibility', 'unicode' => '&#xe84e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'accessible', 'unicode' => '&#xe914;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'account balance', 'unicode' => '&#xe84f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'account balance wallet', 'unicode' => '&#xe850;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'account box', 'unicode' => '&#xe851;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'account circle', 'unicode' => '&#xe853;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'adb', 'unicode' => '&#xe60e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'add', 'unicode' => '&#xe145;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'add a photo', 'unicode' => '&#xe439;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'add alarm', 'unicode' => '&#xe193;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'add alert', 'unicode' => '&#xe003;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'add box', 'unicode' => '&#xe146;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'add circle', 'unicode' => '&#xe147;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'add circle outline', 'unicode' => '&#xe148;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'add location', 'unicode' => '&#xe567;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'add shopping cart', 'unicode' => '&#xe854;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'add to photos', 'unicode' => '&#xe39d;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'add to queue', 'unicode' => '&#xe05c;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'adjust', 'unicode' => '&#xe39e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'airline seat flat', 'unicode' => '&#xe630;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'airline seat flat angled', 'unicode' => '&#xe631;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'airline seat individual suite', 'unicode' => '&#xe632;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'airline seat legroom extra', 'unicode' => '&#xe633;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'airline seat legroom normal', 'unicode' => '&#xe634;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'airline seat legroom reduced', 'unicode' => '&#xe635;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'airline seat recline extra', 'unicode' => '&#xe636;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'airline seat recline normal', 'unicode' => '&#xe637;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'airplanemode active', 'unicode' => '&#xe195;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'airplanemode inactive', 'unicode' => '&#xe194;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'airplay', 'unicode' => '&#xe055;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'airport shuttle', 'unicode' => '&#xeb3c;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'alarm', 'unicode' => '&#xe855;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'alarm add', 'unicode' => '&#xe856;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'alarm off', 'unicode' => '&#xe857;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'alarm on', 'unicode' => '&#xe858;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'album', 'unicode' => '&#xe019;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'all inclusive', 'unicode' => '&#xeb3d;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'all out', 'unicode' => '&#xe90b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'android', 'unicode' => '&#xe859;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'announcement', 'unicode' => '&#xe85a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'apps', 'unicode' => '&#xe5c3;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'archive', 'unicode' => '&#xe149;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'arrow back', 'unicode' => '&#xe5c4;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'arrow downward', 'unicode' => '&#xe5db;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'arrow drop down', 'unicode' => '&#xe5c5;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'arrow drop down circle', 'unicode' => '&#xe5c6;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'arrow drop up', 'unicode' => '&#xe5c7;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'arrow forward', 'unicode' => '&#xe5c8;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'arrow upward', 'unicode' => '&#xe5d8;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'art track', 'unicode' => '&#xe060;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'aspect ratio', 'unicode' => '&#xe85b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'assessment', 'unicode' => '&#xe85c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'assignment', 'unicode' => '&#xe85d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'assignment ind', 'unicode' => '&#xe85e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'assignment late', 'unicode' => '&#xe85f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'assignment return', 'unicode' => '&#xe860;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'assignment returned', 'unicode' => '&#xe861;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'assignment turned in', 'unicode' => '&#xe862;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'assistant', 'unicode' => '&#xe39f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'assistant photo', 'unicode' => '&#xe3a0;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'attach file', 'unicode' => '&#xe226;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'attach money', 'unicode' => '&#xe227;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'attachment', 'unicode' => '&#xe2bc;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'audiotrack', 'unicode' => '&#xe3a1;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'autorenew', 'unicode' => '&#xe863;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'av timer', 'unicode' => '&#xe01b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'backspace', 'unicode' => '&#xe14a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'backup', 'unicode' => '&#xe864;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'battery alert', 'unicode' => '&#xe19c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'battery charging full', 'unicode' => '&#xe1a3;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'battery full', 'unicode' => '&#xe1a4;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'battery std', 'unicode' => '&#xe1a5;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'battery unknown', 'unicode' => '&#xe1a6;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'beach access', 'unicode' => '&#xeb3e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'beenhere', 'unicode' => '&#xe52d;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'block', 'unicode' => '&#xe14b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'bluetooth', 'unicode' => '&#xe1a7;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'bluetooth audio', 'unicode' => '&#xe60f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'bluetooth connected', 'unicode' => '&#xe1a8;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'bluetooth disabled', 'unicode' => '&#xe1a9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'bluetooth searching', 'unicode' => '&#xe1aa;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'blur circular', 'unicode' => '&#xe3a2;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'blur linear', 'unicode' => '&#xe3a3;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'blur off', 'unicode' => '&#xe3a4;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'blur on', 'unicode' => '&#xe3a5;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'book', 'unicode' => '&#xe865;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'bookmark', 'unicode' => '&#xe866;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'bookmark border', 'unicode' => '&#xe867;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'border all', 'unicode' => '&#xe228;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'border bottom', 'unicode' => '&#xe229;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'border clear', 'unicode' => '&#xe22a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'border color', 'unicode' => '&#xe22b;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'border horizontal', 'unicode' => '&#xe22c;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'border inner', 'unicode' => '&#xe22d;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'border left', 'unicode' => '&#xe22e;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'border outer', 'unicode' => '&#xe22f;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'border right', 'unicode' => '&#xe230;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'border style', 'unicode' => '&#xe231;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'border top', 'unicode' => '&#xe232;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'border vertical', 'unicode' => '&#xe233;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'branding watermark', 'unicode' => '&#xe06b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'brightness 1', 'unicode' => '&#xe3a6;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'brightness 2', 'unicode' => '&#xe3a7;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'brightness 3', 'unicode' => '&#xe3a8;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'brightness 4', 'unicode' => '&#xe3a9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'brightness 5', 'unicode' => '&#xe3aa;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'brightness 6', 'unicode' => '&#xe3ab;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'brightness 7', 'unicode' => '&#xe3ac;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'brightness auto', 'unicode' => '&#xe1ab;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'brightness high', 'unicode' => '&#xe1ac;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'brightness low', 'unicode' => '&#xe1ad;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'brightness medium', 'unicode' => '&#xe1ae;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'broken image', 'unicode' => '&#xe3ad;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'brush', 'unicode' => '&#xe3ae;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'bubble chart', 'unicode' => '&#xe6dd;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'bug report', 'unicode' => '&#xe868;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'build', 'unicode' => '&#xe869;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'burst mode', 'unicode' => '&#xe43c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'business', 'unicode' => '&#xe0af;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'business center', 'unicode' => '&#xeb3f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'cached', 'unicode' => '&#xe86a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'cake', 'unicode' => '&#xe7e9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'call', 'unicode' => '&#xe0b0;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'call end', 'unicode' => '&#xe0b1;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'call made', 'unicode' => '&#xe0b2;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'call merge', 'unicode' => '&#xe0b3;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'call missed', 'unicode' => '&#xe0b4;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'call missed outgoing', 'unicode' => '&#xe0e4;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'call received', 'unicode' => '&#xe0b5;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'call split', 'unicode' => '&#xe0b6;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'call to action', 'unicode' => '&#xe06c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'camera', 'unicode' => '&#xe3af;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'camera alt', 'unicode' => '&#xe3b0;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'camera enhance', 'unicode' => '&#xe8fc;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'camera front', 'unicode' => '&#xe3b1;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'camera rear', 'unicode' => '&#xe3b2;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'camera roll', 'unicode' => '&#xe3b3;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'cancel', 'unicode' => '&#xe5c9;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'card giftcard', 'unicode' => '&#xe8f6;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'card membership', 'unicode' => '&#xe8f7;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'card travel', 'unicode' => '&#xe8f8;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'casino', 'unicode' => '&#xeb40;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'cast', 'unicode' => '&#xe307;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'cast connected', 'unicode' => '&#xe308;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'center focus strong', 'unicode' => '&#xe3b4;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'center focus weak', 'unicode' => '&#xe3b5;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'change history', 'unicode' => '&#xe86b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'chat', 'unicode' => '&#xe0b7;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'chat bubble', 'unicode' => '&#xe0ca;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'chat bubble outline', 'unicode' => '&#xe0cb;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'check', 'unicode' => '&#xe5ca;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'check box', 'unicode' => '&#xe834;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'check box outline blank', 'unicode' => '&#xe835;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'check circle', 'unicode' => '&#xe86c;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'chevron left', 'unicode' => '&#xe5cb;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'chevron right', 'unicode' => '&#xe5cc;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'child care', 'unicode' => '&#xeb41;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'child friendly', 'unicode' => '&#xeb42;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'chrome reader mode', 'unicode' => '&#xe86d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'class', 'unicode' => '&#xe86e;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'clear', 'unicode' => '&#xe14c;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'clear all', 'unicode' => '&#xe0b8;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'close', 'unicode' => '&#xe5cd;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'closed caption', 'unicode' => '&#xe01c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'cloud', 'unicode' => '&#xe2bd;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'cloud circle', 'unicode' => '&#xe2be;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'cloud done', 'unicode' => '&#xe2bf;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'cloud download', 'unicode' => '&#xe2c0;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'cloud off', 'unicode' => '&#xe2c1;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'cloud queue', 'unicode' => '&#xe2c2;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'cloud upload', 'unicode' => '&#xe2c3;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'code', 'unicode' => '&#xe86f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'collections', 'unicode' => '&#xe3b6;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'collections bookmark', 'unicode' => '&#xe431;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'color lens', 'unicode' => '&#xe3b7;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'colorize', 'unicode' => '&#xe3b8;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'comment', 'unicode' => '&#xe0b9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'compare', 'unicode' => '&#xe3b9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'compare arrows', 'unicode' => '&#xe915;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'computer', 'unicode' => '&#xe30a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'confirmation number', 'unicode' => '&#xe638;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'contact mail', 'unicode' => '&#xe0d0;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'contact phone', 'unicode' => '&#xe0cf;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'contacts', 'unicode' => '&#xe0ba;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'content copy', 'unicode' => '&#xe14d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'content cut', 'unicode' => '&#xe14e;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'content paste', 'unicode' => '&#xe14f;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'control point', 'unicode' => '&#xe3ba;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'control point duplicate', 'unicode' => '&#xe3bb;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'copyright', 'unicode' => '&#xe90c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'create', 'unicode' => '&#xe150;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'create new folder', 'unicode' => '&#xe2cc;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'credit card', 'unicode' => '&#xe870;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'crop', 'unicode' => '&#xe3be;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'crop 16 9', 'unicode' => '&#xe3bc;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'crop 3 2', 'unicode' => '&#xe3bd;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'crop 5 4', 'unicode' => '&#xe3bf;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'crop 7 5', 'unicode' => '&#xe3c0;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'crop din', 'unicode' => '&#xe3c1;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'crop free', 'unicode' => '&#xe3c2;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'crop landscape', 'unicode' => '&#xe3c3;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'crop original', 'unicode' => '&#xe3c4;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'crop portrait', 'unicode' => '&#xe3c5;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'crop rotate', 'unicode' => '&#xe437;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'crop square', 'unicode' => '&#xe3c6;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'dashboard', 'unicode' => '&#xe871;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'data usage', 'unicode' => '&#xe1af;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'date range', 'unicode' => '&#xe916;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'dehaze', 'unicode' => '&#xe3c7;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'delete', 'unicode' => '&#xe872;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'delete forever', 'unicode' => '&#xe92b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'delete sweep', 'unicode' => '&#xe16c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'description', 'unicode' => '&#xe873;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'desktop mac', 'unicode' => '&#xe30b;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'desktop windows', 'unicode' => '&#xe30c;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'details', 'unicode' => '&#xe3c8;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'developer board', 'unicode' => '&#xe30d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'developer mode', 'unicode' => '&#xe1b0;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'device hub', 'unicode' => '&#xe335;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'devices', 'unicode' => '&#xe1b1;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'devices other', 'unicode' => '&#xe337;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'dialer sip', 'unicode' => '&#xe0bb;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'dialpad', 'unicode' => '&#xe0bc;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'directions', 'unicode' => '&#xe52e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'directions bike', 'unicode' => '&#xe52f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'directions boat', 'unicode' => '&#xe532;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'directions bus', 'unicode' => '&#xe530;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'directions car', 'unicode' => '&#xe531;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'directions railway', 'unicode' => '&#xe534;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'directions run', 'unicode' => '&#xe566;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'directions subway', 'unicode' => '&#xe533;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'directions transit', 'unicode' => '&#xe535;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'directions walk', 'unicode' => '&#xe536;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'disc full', 'unicode' => '&#xe610;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'dns', 'unicode' => '&#xe875;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'do not disturb', 'unicode' => '&#xe612;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'do not disturb alt', 'unicode' => '&#xe611;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'do not disturb off', 'unicode' => '&#xe643;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'do not disturb on', 'unicode' => '&#xe644;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'dock', 'unicode' => '&#xe30e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'domain', 'unicode' => '&#xe7ee;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'done', 'unicode' => '&#xe876;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'done all', 'unicode' => '&#xe877;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'donut large', 'unicode' => '&#xe917;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'donut small', 'unicode' => '&#xe918;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'drafts', 'unicode' => '&#xe151;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'drag handle', 'unicode' => '&#xe25d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'drive eta', 'unicode' => '&#xe613;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'dvr', 'unicode' => '&#xe1b2;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'edit', 'unicode' => '&#xe3c9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'edit location', 'unicode' => '&#xe568;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'eject', 'unicode' => '&#xe8fb;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'email', 'unicode' => '&#xe0be;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'enhanced encryption', 'unicode' => '&#xe63f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'equalizer', 'unicode' => '&#xe01d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'error', 'unicode' => '&#xe000;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'error outline', 'unicode' => '&#xe001;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'euro symbol', 'unicode' => '&#xe926;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'ev station', 'unicode' => '&#xe56d;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'event', 'unicode' => '&#xe878;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'event available', 'unicode' => '&#xe614;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'event busy', 'unicode' => '&#xe615;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'event note', 'unicode' => '&#xe616;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'event seat', 'unicode' => '&#xe903;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'exit to app', 'unicode' => '&#xe879;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'expand less', 'unicode' => '&#xe5ce;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'expand more', 'unicode' => '&#xe5cf;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'explicit', 'unicode' => '&#xe01e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'explore', 'unicode' => '&#xe87a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'exposure', 'unicode' => '&#xe3ca;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'exposure neg 1', 'unicode' => '&#xe3cb;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'exposure neg 2', 'unicode' => '&#xe3cc;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'exposure plus 1', 'unicode' => '&#xe3cd;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'exposure plus 2', 'unicode' => '&#xe3ce;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'exposure zero', 'unicode' => '&#xe3cf;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'extension', 'unicode' => '&#xe87b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'face', 'unicode' => '&#xe87c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'fast forward', 'unicode' => '&#xe01f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'fast rewind', 'unicode' => '&#xe020;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'favorite', 'unicode' => '&#xe87d;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'favorite border', 'unicode' => '&#xe87e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'featured play list', 'unicode' => '&#xe06d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'featured video', 'unicode' => '&#xe06e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'feedback', 'unicode' => '&#xe87f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'fiber dvr', 'unicode' => '&#xe05d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'fiber manual record', 'unicode' => '&#xe061;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'fiber new', 'unicode' => '&#xe05e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'fiber pin', 'unicode' => '&#xe06a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'fiber smart record', 'unicode' => '&#xe062;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'file download', 'unicode' => '&#xe2c4;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'file upload', 'unicode' => '&#xe2c6;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'filter', 'unicode' => '&#xe3d3;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'filter 1', 'unicode' => '&#xe3d0;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'filter 2', 'unicode' => '&#xe3d1;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'filter 3', 'unicode' => '&#xe3d2;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'filter 4', 'unicode' => '&#xe3d4;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'filter 5', 'unicode' => '&#xe3d5;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'filter 6', 'unicode' => '&#xe3d6;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'filter 7', 'unicode' => '&#xe3d7;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'filter 8', 'unicode' => '&#xe3d8;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'filter 9', 'unicode' => '&#xe3d9;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'filter 9 plus', 'unicode' => '&#xe3da;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'filter b and w', 'unicode' => '&#xe3db;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'filter center focus', 'unicode' => '&#xe3dc;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'filter drama', 'unicode' => '&#xe3dd;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'filter frames', 'unicode' => '&#xe3de;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'filter hdr', 'unicode' => '&#xe3df;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'filter list', 'unicode' => '&#xe152;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'filter none', 'unicode' => '&#xe3e0;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'filter tilt shift', 'unicode' => '&#xe3e2;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'filter vintage', 'unicode' => '&#xe3e3;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'find in page', 'unicode' => '&#xe880;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'find replace', 'unicode' => '&#xe881;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'fingerprint', 'unicode' => '&#xe90d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'first page', 'unicode' => '&#xe5dc;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'fitness center', 'unicode' => '&#xeb43;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'flag', 'unicode' => '&#xe153;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'flare', 'unicode' => '&#xe3e4;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'flash auto', 'unicode' => '&#xe3e5;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'flash off', 'unicode' => '&#xe3e6;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'flash on', 'unicode' => '&#xe3e7;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'flight', 'unicode' => '&#xe539;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'flight land', 'unicode' => '&#xe904;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'flight takeoff', 'unicode' => '&#xe905;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'flip', 'unicode' => '&#xe3e8;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'flip to back', 'unicode' => '&#xe882;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'flip to front', 'unicode' => '&#xe883;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'folder', 'unicode' => '&#xe2c7;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'folder open', 'unicode' => '&#xe2c8;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'folder shared', 'unicode' => '&#xe2c9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'folder special', 'unicode' => '&#xe617;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'font download', 'unicode' => '&#xe167;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format align center', 'unicode' => '&#xe234;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format align justify', 'unicode' => '&#xe235;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format align left', 'unicode' => '&#xe236;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format align right', 'unicode' => '&#xe237;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format bold', 'unicode' => '&#xe238;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format clear', 'unicode' => '&#xe239;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format color fill', 'unicode' => '&#xe23a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format color reset', 'unicode' => '&#xe23b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format color text', 'unicode' => '&#xe23c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format indent decrease', 'unicode' => '&#xe23d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format indent increase', 'unicode' => '&#xe23e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format italic', 'unicode' => '&#xe23f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format line spacing', 'unicode' => '&#xe240;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format list bulleted', 'unicode' => '&#xe241;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format list numbered', 'unicode' => '&#xe242;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format paint', 'unicode' => '&#xe243;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format quote', 'unicode' => '&#xe244;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format shapes', 'unicode' => '&#xe25e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format size', 'unicode' => '&#xe245;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format strikethrough', 'unicode' => '&#xe246;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format textdirection l to r', 'unicode' => '&#xe247;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format textdirection r to l', 'unicode' => '&#xe248;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'format underlined', 'unicode' => '&#xe249;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'forum', 'unicode' => '&#xe0bf;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'forward', 'unicode' => '&#xe154;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'forward 10', 'unicode' => '&#xe056;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'forward 30', 'unicode' => '&#xe057;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'forward 5', 'unicode' => '&#xe058;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'free breakfast', 'unicode' => '&#xeb44;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'fullscreen', 'unicode' => '&#xe5d0;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'fullscreen exit', 'unicode' => '&#xe5d1;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'functions', 'unicode' => '&#xe24a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'g translate', 'unicode' => '&#xe927;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'gamepad', 'unicode' => '&#xe30f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'games', 'unicode' => '&#xe021;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'gavel', 'unicode' => '&#xe90e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'gesture', 'unicode' => '&#xe155;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'get app', 'unicode' => '&#xe884;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'gif', 'unicode' => '&#xe908;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'golf course', 'unicode' => '&#xeb45;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'gps fixed', 'unicode' => '&#xe1b3;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'gps not fixed', 'unicode' => '&#xe1b4;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'gps off', 'unicode' => '&#xe1b5;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'grade', 'unicode' => '&#xe885;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'gradient', 'unicode' => '&#xe3e9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'grain', 'unicode' => '&#xe3ea;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'graphic eq', 'unicode' => '&#xe1b8;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'grid off', 'unicode' => '&#xe3eb;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'grid on', 'unicode' => '&#xe3ec;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'group', 'unicode' => '&#xe7ef;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'group add', 'unicode' => '&#xe7f0;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'group work', 'unicode' => '&#xe886;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'hd', 'unicode' => '&#xe052;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'hdr off', 'unicode' => '&#xe3ed;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'hdr on', 'unicode' => '&#xe3ee;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'hdr strong', 'unicode' => '&#xe3f1;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'hdr weak', 'unicode' => '&#xe3f2;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'headset', 'unicode' => '&#xe310;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'headset mic', 'unicode' => '&#xe311;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'healing', 'unicode' => '&#xe3f3;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'hearing', 'unicode' => '&#xe023;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'help', 'unicode' => '&#xe887;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'help outline', 'unicode' => '&#xe8fd;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'high quality', 'unicode' => '&#xe024;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'highlight', 'unicode' => '&#xe25f;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'highlight off', 'unicode' => '&#xe888;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'history', 'unicode' => '&#xe889;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'home', 'unicode' => '&#xe88a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'hot tub', 'unicode' => '&#xeb46;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'hotel', 'unicode' => '&#xe53a;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'hourglass empty', 'unicode' => '&#xe88b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'hourglass full', 'unicode' => '&#xe88c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'http', 'unicode' => '&#xe902;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'https', 'unicode' => '&#xe88d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'image', 'unicode' => '&#xe3f4;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'image aspect ratio', 'unicode' => '&#xe3f5;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'import contacts', 'unicode' => '&#xe0e0;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'import export', 'unicode' => '&#xe0c3;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'important devices', 'unicode' => '&#xe912;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'inbox', 'unicode' => '&#xe156;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'indeterminate check box', 'unicode' => '&#xe909;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'info', 'unicode' => '&#xe88e;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'info outline', 'unicode' => '&#xe88f;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'input', 'unicode' => '&#xe890;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'insert chart', 'unicode' => '&#xe24b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'insert comment', 'unicode' => '&#xe24c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'insert drive file', 'unicode' => '&#xe24d;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'insert emoticon', 'unicode' => '&#xe24e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'insert invitation', 'unicode' => '&#xe24f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'insert link', 'unicode' => '&#xe250;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'insert photo', 'unicode' => '&#xe251;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'invert colors', 'unicode' => '&#xe891;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'invert colors off', 'unicode' => '&#xe0c4;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'iso', 'unicode' => '&#xe3f6;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'keyboard', 'unicode' => '&#xe312;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'keyboard arrow down', 'unicode' => '&#xe313;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'keyboard arrow left', 'unicode' => '&#xe314;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'keyboard arrow right', 'unicode' => '&#xe315;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'keyboard arrow up', 'unicode' => '&#xe316;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'keyboard backspace', 'unicode' => '&#xe317;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'keyboard capslock', 'unicode' => '&#xe318;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'keyboard hide', 'unicode' => '&#xe31a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'keyboard return', 'unicode' => '&#xe31b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'keyboard tab', 'unicode' => '&#xe31c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'keyboard voice', 'unicode' => '&#xe31d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'kitchen', 'unicode' => '&#xeb47;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'label', 'unicode' => '&#xe892;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'label outline', 'unicode' => '&#xe893;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'landscape', 'unicode' => '&#xe3f7;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'language', 'unicode' => '&#xe894;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'laptop', 'unicode' => '&#xe31e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'laptop chromebook', 'unicode' => '&#xe31f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'laptop mac', 'unicode' => '&#xe320;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'laptop windows', 'unicode' => '&#xe321;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'last page', 'unicode' => '&#xe5dd;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'launch', 'unicode' => '&#xe895;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'layers', 'unicode' => '&#xe53b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'layers clear', 'unicode' => '&#xe53c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'leak add', 'unicode' => '&#xe3f8;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'leak remove', 'unicode' => '&#xe3f9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'lens', 'unicode' => '&#xe3fa;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'library add', 'unicode' => '&#xe02e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'library books', 'unicode' => '&#xe02f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'library music', 'unicode' => '&#xe030;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'lightbulb outline', 'unicode' => '&#xe90f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'line style', 'unicode' => '&#xe919;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'line weight', 'unicode' => '&#xe91a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'linear scale', 'unicode' => '&#xe260;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'link', 'unicode' => '&#xe157;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'linked camera', 'unicode' => '&#xe438;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'list', 'unicode' => '&#xe896;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'live help', 'unicode' => '&#xe0c6;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'live tv', 'unicode' => '&#xe639;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local activity', 'unicode' => '&#xe53f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local airport', 'unicode' => '&#xe53d;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'local atm', 'unicode' => '&#xe53e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local bar', 'unicode' => '&#xe540;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local cafe', 'unicode' => '&#xe541;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local car wash', 'unicode' => '&#xe542;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local convenience store', 'unicode' => '&#xe543;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local dining', 'unicode' => '&#xe556;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local drink', 'unicode' => '&#xe544;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local florist', 'unicode' => '&#xe545;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local gas station', 'unicode' => '&#xe546;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local grocery store', 'unicode' => '&#xe547;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local hospital', 'unicode' => '&#xe548;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local hotel', 'unicode' => '&#xe549;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local laundry service', 'unicode' => '&#xe54a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local library', 'unicode' => '&#xe54b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local mall', 'unicode' => '&#xe54c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local movies', 'unicode' => '&#xe54d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local offer', 'unicode' => '&#xe54e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local parking', 'unicode' => '&#xe54f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local pharmacy', 'unicode' => '&#xe550;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local phone', 'unicode' => '&#xe551;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local pizza', 'unicode' => '&#xe552;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local play', 'unicode' => '&#xe553;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local post office', 'unicode' => '&#xe554;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local printshop', 'unicode' => '&#xe555;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local see', 'unicode' => '&#xe557;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local shipping', 'unicode' => '&#xe558;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'local taxi', 'unicode' => '&#xe559;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'location city', 'unicode' => '&#xe7f1;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'location disabled', 'unicode' => '&#xe1b6;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'location off', 'unicode' => '&#xe0c7;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'location on', 'unicode' => '&#xe0c8;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'location searching', 'unicode' => '&#xe1b7;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'lock', 'unicode' => '&#xe897;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'lock open', 'unicode' => '&#xe898;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'lock outline', 'unicode' => '&#xe899;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'looks', 'unicode' => '&#xe3fc;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'looks 3', 'unicode' => '&#xe3fb;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'looks 4', 'unicode' => '&#xe3fd;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'looks 5', 'unicode' => '&#xe3fe;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'looks 6', 'unicode' => '&#xe3ff;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'looks one', 'unicode' => '&#xe400;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'looks two', 'unicode' => '&#xe401;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'loop', 'unicode' => '&#xe028;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'loupe', 'unicode' => '&#xe402;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'low priority', 'unicode' => '&#xe16d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'loyalty', 'unicode' => '&#xe89a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'mail', 'unicode' => '&#xe158;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'mail outline', 'unicode' => '&#xe0e1;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'map', 'unicode' => '&#xe55b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'markunread', 'unicode' => '&#xe159;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'markunread mailbox', 'unicode' => '&#xe89b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'memory', 'unicode' => '&#xe322;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'menu', 'unicode' => '&#xe5d2;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'merge type', 'unicode' => '&#xe252;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'message', 'unicode' => '&#xe0c9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'mic', 'unicode' => '&#xe029;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'mic none', 'unicode' => '&#xe02a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'mic off', 'unicode' => '&#xe02b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'mms', 'unicode' => '&#xe618;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'mode comment', 'unicode' => '&#xe253;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'mode edit', 'unicode' => '&#xe254;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'monetization on', 'unicode' => '&#xe263;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'money off', 'unicode' => '&#xe25c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'monochrome photos', 'unicode' => '&#xe403;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'mood', 'unicode' => '&#xe7f2;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'mood bad', 'unicode' => '&#xe7f3;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'more', 'unicode' => '&#xe619;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'more horiz', 'unicode' => '&#xe5d3;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'more vert', 'unicode' => '&#xe5d4;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'motorcycle', 'unicode' => '&#xe91b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'mouse', 'unicode' => '&#xe323;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'move to inbox', 'unicode' => '&#xe168;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'movie', 'unicode' => '&#xe02c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'movie creation', 'unicode' => '&#xe404;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'movie filter', 'unicode' => '&#xe43a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'multiline chart', 'unicode' => '&#xe6df;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'music note', 'unicode' => '&#xe405;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'music video', 'unicode' => '&#xe063;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'my location', 'unicode' => '&#xe55c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'nature', 'unicode' => '&#xe406;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'nature people', 'unicode' => '&#xe407;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'navigate before', 'unicode' => '&#xe408;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'navigate next', 'unicode' => '&#xe409;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'navigation', 'unicode' => '&#xe55d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'near me', 'unicode' => '&#xe569;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'network cell', 'unicode' => '&#xe1b9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'network check', 'unicode' => '&#xe640;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'network locked', 'unicode' => '&#xe61a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'network wifi', 'unicode' => '&#xe1ba;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'new releases', 'unicode' => '&#xe031;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'next week', 'unicode' => '&#xe16a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'nfc', 'unicode' => '&#xe1bb;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'no encryption', 'unicode' => '&#xe641;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'no sim', 'unicode' => '&#xe0cc;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'not interested', 'unicode' => '&#xe033;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'note', 'unicode' => '&#xe06f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'note add', 'unicode' => '&#xe89c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'notifications', 'unicode' => '&#xe7f4;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'notifications active', 'unicode' => '&#xe7f7;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'notifications none', 'unicode' => '&#xe7f5;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'notifications off', 'unicode' => '&#xe7f6;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'notifications paused', 'unicode' => '&#xe7f8;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'offline pin', 'unicode' => '&#xe90a;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'ondemand video', 'unicode' => '&#xe63a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'opacity', 'unicode' => '&#xe91c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'open in browser', 'unicode' => '&#xe89d;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'open in new', 'unicode' => '&#xe89e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'open with', 'unicode' => '&#xe89f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'pages', 'unicode' => '&#xe7f9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'pageview', 'unicode' => '&#xe8a0;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'palette', 'unicode' => '&#xe40a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'pan tool', 'unicode' => '&#xe925;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'panorama', 'unicode' => '&#xe40b;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'panorama fish eye', 'unicode' => '&#xe40c;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'panorama horizontal', 'unicode' => '&#xe40d;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'panorama vertical', 'unicode' => '&#xe40e;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'panorama wide angle', 'unicode' => '&#xe40f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'party mode', 'unicode' => '&#xe7fa;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'pause', 'unicode' => '&#xe034;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'pause circle filled', 'unicode' => '&#xe035;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'pause circle outline', 'unicode' => '&#xe036;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'payment', 'unicode' => '&#xe8a1;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'people', 'unicode' => '&#xe7fb;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'people outline', 'unicode' => '&#xe7fc;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'perm camera mic', 'unicode' => '&#xe8a2;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'perm contact calendar', 'unicode' => '&#xe8a3;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'perm data setting', 'unicode' => '&#xe8a4;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'perm device information', 'unicode' => '&#xe8a5;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'perm identity', 'unicode' => '&#xe8a6;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'perm media', 'unicode' => '&#xe8a7;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'perm phone msg', 'unicode' => '&#xe8a8;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'perm scan wifi', 'unicode' => '&#xe8a9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'person', 'unicode' => '&#xe7fd;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'person add', 'unicode' => '&#xe7fe;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'person outline', 'unicode' => '&#xe7ff;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'person pin', 'unicode' => '&#xe55a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'person pin circle', 'unicode' => '&#xe56a;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'personal video', 'unicode' => '&#xe63b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'pets', 'unicode' => '&#xe91d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'phone', 'unicode' => '&#xe0cd;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'phone android', 'unicode' => '&#xe324;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'phone bluetooth speaker', 'unicode' => '&#xe61b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'phone forwarded', 'unicode' => '&#xe61c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'phone in talk', 'unicode' => '&#xe61d;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'phone iphone', 'unicode' => '&#xe325;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'phone locked', 'unicode' => '&#xe61e;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'phone missed', 'unicode' => '&#xe61f;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'phone paused', 'unicode' => '&#xe620;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'phonelink', 'unicode' => '&#xe326;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'phonelink erase', 'unicode' => '&#xe0db;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'phonelink lock', 'unicode' => '&#xe0dc;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'phonelink off', 'unicode' => '&#xe327;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'phonelink ring', 'unicode' => '&#xe0dd;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'phonelink setup', 'unicode' => '&#xe0de;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'photo', 'unicode' => '&#xe410;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'photo album', 'unicode' => '&#xe411;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'photo camera', 'unicode' => '&#xe412;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'photo filter', 'unicode' => '&#xe43b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'photo library', 'unicode' => '&#xe413;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'photo size select actual', 'unicode' => '&#xe432;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'photo size select large', 'unicode' => '&#xe433;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'photo size select small', 'unicode' => '&#xe434;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'picture as pdf', 'unicode' => '&#xe415;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'picture in picture', 'unicode' => '&#xe8aa;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'picture in picture alt', 'unicode' => '&#xe911;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'pie chart', 'unicode' => '&#xe6c4;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'pie chart outlined', 'unicode' => '&#xe6c5;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'pin drop', 'unicode' => '&#xe55e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'place', 'unicode' => '&#xe55f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'play arrow', 'unicode' => '&#xe037;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'play circle filled', 'unicode' => '&#xe038;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'play circle outline', 'unicode' => '&#xe039;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'play for work', 'unicode' => '&#xe906;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'playlist add', 'unicode' => '&#xe03b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'playlist add check', 'unicode' => '&#xe065;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'playlist play', 'unicode' => '&#xe05f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'plus one', 'unicode' => '&#xe800;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'poll', 'unicode' => '&#xe801;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'polymer', 'unicode' => '&#xe8ab;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'pool', 'unicode' => '&#xeb48;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'portable wifi off', 'unicode' => '&#xe0ce;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'portrait', 'unicode' => '&#xe416;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'power', 'unicode' => '&#xe63c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'power input', 'unicode' => '&#xe336;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'power settings new', 'unicode' => '&#xe8ac;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'pregnant woman', 'unicode' => '&#xe91e;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'present to all', 'unicode' => '&#xe0df;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'print', 'unicode' => '&#xe8ad;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'priority high', 'unicode' => '&#xe645;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'public', 'unicode' => '&#xe80b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'publish', 'unicode' => '&#xe255;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'query builder', 'unicode' => '&#xe8ae;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'question answer', 'unicode' => '&#xe8af;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'queue', 'unicode' => '&#xe03c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'queue music', 'unicode' => '&#xe03d;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'queue play next', 'unicode' => '&#xe066;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'radio', 'unicode' => '&#xe03e;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'radio button checked', 'unicode' => '&#xe837;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'radio button unchecked', 'unicode' => '&#xe836;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'rate review', 'unicode' => '&#xe560;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'receipt', 'unicode' => '&#xe8b0;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'recent actors', 'unicode' => '&#xe03f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'record voice over', 'unicode' => '&#xe91f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'redeem', 'unicode' => '&#xe8b1;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'redo', 'unicode' => '&#xe15a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'refresh', 'unicode' => '&#xe5d5;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'remove', 'unicode' => '&#xe15b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'remove circle', 'unicode' => '&#xe15c;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'remove circle outline', 'unicode' => '&#xe15d;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'remove from queue', 'unicode' => '&#xe067;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'remove red eye', 'unicode' => '&#xe417;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'remove shopping cart', 'unicode' => '&#xe928;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'reorder', 'unicode' => '&#xe8fe;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'repeat', 'unicode' => '&#xe040;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'repeat one', 'unicode' => '&#xe041;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'replay', 'unicode' => '&#xe042;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'replay 10', 'unicode' => '&#xe059;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'replay 30', 'unicode' => '&#xe05a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'replay 5', 'unicode' => '&#xe05b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'reply', 'unicode' => '&#xe15e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'reply all', 'unicode' => '&#xe15f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'report', 'unicode' => '&#xe160;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'report problem', 'unicode' => '&#xe8b2;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'restaurant', 'unicode' => '&#xe56c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'restaurant menu', 'unicode' => '&#xe561;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'restore', 'unicode' => '&#xe8b3;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'restore page', 'unicode' => '&#xe929;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'ring volume', 'unicode' => '&#xe0d1;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'room', 'unicode' => '&#xe8b4;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'room service', 'unicode' => '&#xeb49;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'rotate 90 degrees ccw', 'unicode' => '&#xe418;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'rotate left', 'unicode' => '&#xe419;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'rotate right', 'unicode' => '&#xe41a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'rounded corner', 'unicode' => '&#xe920;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'router', 'unicode' => '&#xe328;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'rowing', 'unicode' => '&#xe921;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'rss feed', 'unicode' => '&#xe0e5;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'rv hookup', 'unicode' => '&#xe642;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'satellite', 'unicode' => '&#xe562;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'save', 'unicode' => '&#xe161;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'scanner', 'unicode' => '&#xe329;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'schedule', 'unicode' => '&#xe8b5;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'school', 'unicode' => '&#xe80c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'screen lock landscape', 'unicode' => '&#xe1be;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'screen lock portrait', 'unicode' => '&#xe1bf;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'screen lock rotation', 'unicode' => '&#xe1c0;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'screen rotation', 'unicode' => '&#xe1c1;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'screen share', 'unicode' => '&#xe0e2;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'sd card', 'unicode' => '&#xe623;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'sd storage', 'unicode' => '&#xe1c2;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'search', 'unicode' => '&#xe8b6;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'security', 'unicode' => '&#xe32a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'select all', 'unicode' => '&#xe162;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'send', 'unicode' => '&#xe163;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'sentiment dissatisfied', 'unicode' => '&#xe811;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'sentiment neutral', 'unicode' => '&#xe812;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'sentiment satisfied', 'unicode' => '&#xe813;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'sentiment very dissatisfied', 'unicode' => '&#xe814;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'sentiment very satisfied', 'unicode' => '&#xe815;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'settings', 'unicode' => '&#xe8b8;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'settings applications', 'unicode' => '&#xe8b9;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'settings backup restore', 'unicode' => '&#xe8ba;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'settings bluetooth', 'unicode' => '&#xe8bb;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'settings brightness', 'unicode' => '&#xe8bd;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'settings cell', 'unicode' => '&#xe8bc;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'settings ethernet', 'unicode' => '&#xe8be;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'settings input antenna', 'unicode' => '&#xe8bf;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'settings input component', 'unicode' => '&#xe8c0;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'settings input composite', 'unicode' => '&#xe8c1;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'settings input hdmi', 'unicode' => '&#xe8c2;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'settings input svideo', 'unicode' => '&#xe8c3;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'settings overscan', 'unicode' => '&#xe8c4;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'settings phone', 'unicode' => '&#xe8c5;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'settings power', 'unicode' => '&#xe8c6;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'settings remote', 'unicode' => '&#xe8c7;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'settings system daydream', 'unicode' => '&#xe1c3;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'settings voice', 'unicode' => '&#xe8c8;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'share', 'unicode' => '&#xe80d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'shop', 'unicode' => '&#xe8c9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'shop two', 'unicode' => '&#xe8ca;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'shopping basket', 'unicode' => '&#xe8cb;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'shopping cart', 'unicode' => '&#xe8cc;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'short text', 'unicode' => '&#xe261;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'show chart', 'unicode' => '&#xe6e1;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'shuffle', 'unicode' => '&#xe043;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'signal cellular 4 bar', 'unicode' => '&#xe1c8;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'signal cellular connected no internet 4 bar', 'unicode' => '&#xe1cd;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'signal cellular no sim', 'unicode' => '&#xe1ce;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'signal cellular null', 'unicode' => '&#xe1cf;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'signal cellular off', 'unicode' => '&#xe1d0;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'signal wifi 4 bar', 'unicode' => '&#xe1d8;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'signal wifi 4 bar lock', 'unicode' => '&#xe1d9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'signal wifi off', 'unicode' => '&#xe1da;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'sim card', 'unicode' => '&#xe32b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'sim card alert', 'unicode' => '&#xe624;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'skip next', 'unicode' => '&#xe044;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'skip previous', 'unicode' => '&#xe045;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'slideshow', 'unicode' => '&#xe41b;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'slow motion video', 'unicode' => '&#xe068;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'smartphone', 'unicode' => '&#xe32c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'smoke free', 'unicode' => '&#xeb4a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'smoking rooms', 'unicode' => '&#xeb4b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'sms', 'unicode' => '&#xe625;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'sms failed', 'unicode' => '&#xe626;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'snooze', 'unicode' => '&#xe046;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'sort', 'unicode' => '&#xe164;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'sort by alpha', 'unicode' => '&#xe053;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'spa', 'unicode' => '&#xeb4c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'space bar', 'unicode' => '&#xe256;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'speaker', 'unicode' => '&#xe32d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'speaker group', 'unicode' => '&#xe32e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'speaker notes', 'unicode' => '&#xe8cd;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'speaker notes off', 'unicode' => '&#xe92a;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'speaker phone', 'unicode' => '&#xe0d2;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'spellcheck', 'unicode' => '&#xe8ce;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'star', 'unicode' => '&#xe838;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'star border', 'unicode' => '&#xe83a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'star half', 'unicode' => '&#xe839;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'stars', 'unicode' => '&#xe8d0;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'stay current landscape', 'unicode' => '&#xe0d3;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'stay current portrait', 'unicode' => '&#xe0d4;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'stay primary landscape', 'unicode' => '&#xe0d5;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'stay primary portrait', 'unicode' => '&#xe0d6;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'stop', 'unicode' => '&#xe047;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'stop screen share', 'unicode' => '&#xe0e3;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'storage', 'unicode' => '&#xe1db;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'store', 'unicode' => '&#xe8d1;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'store mall directory', 'unicode' => '&#xe563;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'straighten', 'unicode' => '&#xe41c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'streetview', 'unicode' => '&#xe56e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'strikethrough s', 'unicode' => '&#xe257;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'style', 'unicode' => '&#xe41d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'subdirectory arrow left', 'unicode' => '&#xe5d9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'subdirectory arrow right', 'unicode' => '&#xe5da;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'subject', 'unicode' => '&#xe8d2;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'subscriptions', 'unicode' => '&#xe064;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'subtitles', 'unicode' => '&#xe048;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'subway', 'unicode' => '&#xe56f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'supervisor account', 'unicode' => '&#xe8d3;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'surround sound', 'unicode' => '&#xe049;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'swap calls', 'unicode' => '&#xe0d7;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'swap horiz', 'unicode' => '&#xe8d4;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'swap vert', 'unicode' => '&#xe8d5;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'swap vertical circle', 'unicode' => '&#xe8d6;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'switch camera', 'unicode' => '&#xe41e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'switch video', 'unicode' => '&#xe41f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'sync', 'unicode' => '&#xe627;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'sync disabled', 'unicode' => '&#xe628;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'sync problem', 'unicode' => '&#xe629;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'system update', 'unicode' => '&#xe62a;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'system update alt', 'unicode' => '&#xe8d7;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'tab', 'unicode' => '&#xe8d8;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'tab unselected', 'unicode' => '&#xe8d9;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'tablet', 'unicode' => '&#xe32f;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'tablet android', 'unicode' => '&#xe330;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'tablet mac', 'unicode' => '&#xe331;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'tag faces', 'unicode' => '&#xe420;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'tap and play', 'unicode' => '&#xe62b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'terrain', 'unicode' => '&#xe564;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'text fields', 'unicode' => '&#xe262;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'text format', 'unicode' => '&#xe165;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'textsms', 'unicode' => '&#xe0d8;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'texture', 'unicode' => '&#xe421;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'theaters', 'unicode' => '&#xe8da;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'thumb down', 'unicode' => '&#xe8db;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'thumb up', 'unicode' => '&#xe8dc;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'thumbs up down', 'unicode' => '&#xe8dd;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'time to leave', 'unicode' => '&#xe62c;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'timelapse', 'unicode' => '&#xe422;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'timeline', 'unicode' => '&#xe922;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'timer', 'unicode' => '&#xe425;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'timer 10', 'unicode' => '&#xe423;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'timer 3', 'unicode' => '&#xe424;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'timer off', 'unicode' => '&#xe426;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'title', 'unicode' => '&#xe264;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'toc', 'unicode' => '&#xe8de;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'today', 'unicode' => '&#xe8df;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'toll', 'unicode' => '&#xe8e0;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'tonality', 'unicode' => '&#xe427;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'touch app', 'unicode' => '&#xe913;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'toys', 'unicode' => '&#xe332;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'track changes', 'unicode' => '&#xe8e1;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'traffic', 'unicode' => '&#xe565;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'train', 'unicode' => '&#xe570;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'tram', 'unicode' => '&#xe571;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'transfer within a station', 'unicode' => '&#xe572;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'transform', 'unicode' => '&#xe428;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'translate', 'unicode' => '&#xe8e2;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'trending down', 'unicode' => '&#xe8e3;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'trending flat', 'unicode' => '&#xe8e4;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'trending up', 'unicode' => '&#xe8e5;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'tune', 'unicode' => '&#xe429;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'turned in', 'unicode' => '&#xe8e6;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'turned in not', 'unicode' => '&#xe8e7;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'tv', 'unicode' => '&#xe333;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'unarchive', 'unicode' => '&#xe169;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'undo', 'unicode' => '&#xe166;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'unfold less', 'unicode' => '&#xe5d6;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'unfold more', 'unicode' => '&#xe5d7;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'update', 'unicode' => '&#xe923;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'usb', 'unicode' => '&#xe1e0;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'verified user', 'unicode' => '&#xe8e8;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'vertical align bottom', 'unicode' => '&#xe258;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'vertical align center', 'unicode' => '&#xe259;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'vertical align top', 'unicode' => '&#xe25a;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'vibration', 'unicode' => '&#xe62d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'video call', 'unicode' => '&#xe070;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'video label', 'unicode' => '&#xe071;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'video library', 'unicode' => '&#xe04a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'videocam', 'unicode' => '&#xe04b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'videocam off', 'unicode' => '&#xe04c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'videogame asset', 'unicode' => '&#xe338;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'view agenda', 'unicode' => '&#xe8e9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'view array', 'unicode' => '&#xe8ea;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'view carousel', 'unicode' => '&#xe8eb;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'view column', 'unicode' => '&#xe8ec;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'view comfy', 'unicode' => '&#xe42a;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'view compact', 'unicode' => '&#xe42b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'view day', 'unicode' => '&#xe8ed;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'view headline', 'unicode' => '&#xe8ee;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'view list', 'unicode' => '&#xe8ef;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'view module', 'unicode' => '&#xe8f0;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'view quilt', 'unicode' => '&#xe8f1;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'view stream', 'unicode' => '&#xe8f2;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'view week', 'unicode' => '&#xe8f3;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'vignette', 'unicode' => '&#xe435;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'visibility', 'unicode' => '&#xe8f4;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'visibility off', 'unicode' => '&#xe8f5;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'voice chat', 'unicode' => '&#xe62e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'voicemail', 'unicode' => '&#xe0d9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'volume down', 'unicode' => '&#xe04d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'volume mute', 'unicode' => '&#xe04e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'volume off', 'unicode' => '&#xe04f;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'volume up', 'unicode' => '&#xe050;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'vpn key', 'unicode' => '&#xe0da;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'vpn lock', 'unicode' => '&#xe62f;'],
	['family' => 'material', 'style' => 'outline', 'name' => 'wallpaper', 'unicode' => '&#xe1bc;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'warning', 'unicode' => '&#xe002;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'watch', 'unicode' => '&#xe334;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'watch later', 'unicode' => '&#xe924;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'wb auto', 'unicode' => '&#xe42c;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'wb cloudy', 'unicode' => '&#xe42d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'wb incandescent', 'unicode' => '&#xe42e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'wb iridescent', 'unicode' => '&#xe436;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'wb sunny', 'unicode' => '&#xe430;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'wc', 'unicode' => '&#xe63d;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'web', 'unicode' => '&#xe051;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'web asset', 'unicode' => '&#xe069;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'weekend', 'unicode' => '&#xe16b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'whatshot', 'unicode' => '&#xe80e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'widgets', 'unicode' => '&#xe1bd;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'wifi', 'unicode' => '&#xe63e;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'wifi lock', 'unicode' => '&#xe1e1;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'wifi tethering', 'unicode' => '&#xe1e2;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'work', 'unicode' => '&#xe8f9;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'wrap text', 'unicode' => '&#xe25b;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'youtube searched for', 'unicode' => '&#xe8fa;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'zoom in', 'unicode' => '&#xe8ff;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'zoom out', 'unicode' => '&#xe900;'],
	['family' => 'material', 'style' => 'solid', 'name' => 'zoom out map', 'unicode' => '&#xe56b;'],
];
